import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SectionHeader from "@/components/molecules/SectionHeader";
import { BsBoxSeam } from "react-icons/bs";
import { FaPlus } from "react-icons/fa6";
import StatCard from "@/components/molecules/StatCard";
import { HiArrowTrendingUp, IoIosMic, LuCircleCheckBig, RiUser3Line } from "@/app/icons";
import InputField from "@/components/atoms/InputField";
import EmptyState from "@/components/molecules/EmptyState";
import AddLendingModal from "@/components/organisms/AddLendingModal";
import AdvanceButton from "@/components/atoms/ActionButton";
import CardsWithSwitchButtons from "@/components/molecules/CardWithSwitchButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    // const [activeTab, setActiveTab] = useState<number>(0);
    // const [isAddUser, setIsAddUser] = useState<boolean>(false);
    // const [selectedTab, setSelectedTab] = useState<"active" | "returned">("active");
  
    // const router = useRouter()
  
    // const handleTabClick = (tab: "active" | "returned") => {
    //   setSelectedTab(tab);
    //   router.push(tab)
    //   console.log("Selected:", tab);
    // };
  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="w-full min-h-screen bg-(--color-bg-primary) text-(--color-text-primary)">
          <div className="max-w-[1280px] mx-auto flex flex-col px-6 py-6 gap-6">
            <SectionHeader
              icon={<BsBoxSeam className="text-xl" />}
              title="Shop Tracker"
              subtitle="Track lending by person"
              actionLabel="Add New"
              actionIcon={<FaPlus />}
            // onAction={() => setIsAddUser(prev => !prev)}
            />

            <div className="flex flex-wrap gap-4">
              <StatCard
                icon={<RiUser3Line className="text-xl" />}
                value={'4'}
                label="People"
                className="basis-[220px] border-(--border-people-card) bg-(--color-bg-primary)"
                iconClassName="bg-(--color-primary-soft) text-(--color-primary)"
                labelClassName="text-(--color-primary)"
              />
              <StatCard
                icon={<HiArrowTrendingUp className="text-xl" />}
                value={'3'}
                label="Active"
                className="basis-[220px] border-(--border-active-card) bg-(--color-warning-bg)"
                iconClassName="bg-(--color-secondary-soft) text-(--color-text-warning)"
                labelClassName="text-(--color-text-warning)"
              />
              <StatCard
                icon={<LuCircleCheckBig className="text-xl" />}
                value={1}
                label="Returned"
                className="basis-[220px] border-(--border-returned-card) bg-(--color-success-bg)"
                iconClassName="bg-(--color-tertiary-soft) text-(--color-text-success)"
                labelClassName="text-(--color-text-success)"
              />
            </div>

            <InputField
              icon={<RiUser3Line className="text-xl" />}
              placeholder="Search by person name..."
              actionLabel="Speak"
              actionIcon={<IoIosMic />}
            />

          </div>
          <div className="max-w-[1280px] mx-auto flex flex-col px-6 pb-12">
            <CardsWithSwitchButtons children={children}/>        
          </div>
        </section>
      </body>
    </html>
  );
}
